name: ML CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    # Checkout repo
    - name: Checkout
      uses: actions/checkout@v3

    # Setup Python
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    # Install DVC
    - name: Install DVC
      run: |
        pip install dvc-gs

    # Auth Google Cloud
    - name: Authenticate to GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_KEY }}

    # Pull model
    - name: DVC Pull
      run: |
        dvc pull

    # Setup gcloud
    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: vertex-ai-demo-457907

    # Configure Docker
    - name: Configure Docker
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev

    # Build Image
    - name: Build Docker Image
      run: |
        docker build -t us-central1-docker.pkg.dev/vertex-ai-demo-457907/ml-repo/ml-app:latest .


    # Push Image
    - name: Push Image
      run: |
        docker push us-central1-docker.pkg.dev/vertex-ai-demo-457907/ml-repo/ml-app:latest

    # Deploy to Cloud Run
    - name: Deploy
      run: |
        gcloud run deploy ml-app \
          --image us-central1-docker.pkg.dev/vertex-ai-demo-457907/ml-repo/ml-app:latest \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --timeout=600 \
          --memory=2Gi
          
